# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api-consumer-lancamento:
    image: api-consumer-lancamento
    build:
      context: .
      dockerfile: NFT/Api/Consumer/Lancamento/Dockerfile
    ports:
      - 5093:5093
