version: '3.4'

services:
  wallet-nft:
    image: ${DOCKER_REGISTRY-}wallet-nft
    build:
      context: .
      dockerfile: Wallet.NFT/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
