@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

' This is a comment on a single line
User->App : Lançamentos
/' You quote alors use slash-and-quote
to split your comments on several
lines '/

Container(spa, "NFT ", "Razor", "Entrada para os efetuar os lançamentos e obter o relatorio diario.")
'Container(ma, "Mobile App", "Xamarin", "Provides a limited subset ot the internet banking functionality to customers via their mobile mobile device.")
Container(db, "Database", "Relational Database Schema", "Base de dados que contem os dados referentes ao usuário e seus lancamentos na wallet.")

'System_Ext(mbs, "Mainframe Banking System", "Stores all of the core wallet information about transactions.")

Container_Boundary(api, "API Gateway") {
    Component(sign, "Lançamentos", "Producer Controle Lancamento.", "Função de distribuição dos services. ?")
    Component(accounts, "Consolidados", "Producer Controle Consolidado.", "Relatorios dos lancamento diario.")
    Component(security, "Security Component", "Spring Bean", "Provides functionality related to singing in, changing passwords, etc.")   
}

Rel(spa, sign, "Uses", "JSON/HTTPS")
Rel(spa, accounts, "Uses", "JSON/HTTPS")


@enduml
